# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Top11' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Top11
	pod 'Alamofire'
  	pod 'SnapKit'
  	pod 'Kingfisher'
  	pod 'R.swift'
	pod 'RxSwift'
	pod 'RxCocoa'

	pod 'MaterialComponents/BottomNavigation'
	pod 'MaterialComponents/Buttons'
	pod 'MaterialComponents/Snackbar'
	pod 'MaterialComponents/TextControls+FilledTextAreas'
	pod 'MaterialComponents/TextControls+FilledTextFields'
end
