source 'https://cdn.cocoapods.org/'
install! 'cocoapods',
:generate_multiple_pod_projects => true,
:incremental_installation => true
platform :ios, '14.0'
workspace 'MVVM_architecture_example'
# Common pods

def common_pods
  pod 'Alamofire'
  pod 'SnapKit'
  pod 'Kingfisher'
  pod 'R.swift'
end


target 'MVVM_architecture_example' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  project 'MVVM_architecture_example.xcodeproj'
  use_frameworks!
  common_pods
end

