# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxMovies' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxMovies
	pod 'Alamofire'
  	pod 'SnapKit'
  	pod 'Kingfisher'
  	pod 'R.swift'
	pod 'RxSwift'
	pod 'RxCocoa'
end
